import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

/*
  pages/api : handling rest api similar to expressjs
  pages/files.js : reactjs components
*/


export default function Home() {
  const [books, setBooks] = useState([])
  const [title, setTitle] = useState([])
  const [pages, setPages] = useState([])
  const [lan, setLan] = useState([])
  const fetchBooks = async () => {
    console.log("fetching started");
    const response = await fetch('/api/books')
    const data = await response.json()
    console.log(data)
    setBooks(data)
  }
  const submitBook = async () => {
    const response = await fetch('/api/books', {
      method: 'POST',
      body: JSON.stringify({
        title,
        pages,
        language: lan
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    })
    const data = await response.json()
    setBooks([data])
    console.log(data)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div align="center">
        {"Title: "}<input
          type='text'
          value={title}
          onChange={e => setTitle(e.target.value)}
        />
        <br/>
        {"Pages: "}<input
          type='text'
          value={pages}
          onChange={e => setPages(e.target.value)}
        />
        <br/>
        {"Language: "}<input
          type='text'
          value={lan}
          onChange={e => setLan(e.target.value)}
        />
        <br/>
        <button onClick={submitBook}>Submit book</button>
    </div>

        <button  onClick={fetchBooks}>Get the latest books</button>

        <div className={styles.grid}>
        {
      books.map(book => {
        return (
          <div align="center" key={book.id} className={styles.card}>
            {book.id}.<br/>
            {"Title: "}{book.title}.<br/>
            {"Pages: "} {book.pages}.<br/>
            {"Language: "}{book.language} <br/>
            <hr/>
          </div>
        )
      })
    }
        </div>

     
      
      
      </main>



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
